version: '3.9'

services:
  postgis:
    container_name: postgis
    image: postgis/postgis
    environment:
      POSTGRES_DB: BAG
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: Geheim1!
      PGDATA: /var/lib/postgis/data
    volumes:
      - ./postgis/postgis-data:/var/lib/postgis/data
      - ./postgis/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: on-failure
    shm_size: '4g'
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@database.org
      PGADMIN_DEFAULT_PASSWORD: Geheim1!
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    depends_on:
      - postgis
    links:
      - postgis:postgis-db
    volumes: 
      - ./pgadmin/servers.json:/pgadmin4/servers.json