version: '3.9'

services:
  db:
    container_name: postgis
    image: postgis-population-service
    env_file:
      - .env
    volumes:
      - pop-data:/var/libe/postgis/data
    ports:
      - 5432:5432
    restart: on-failure
    shm_size: '4g'
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@database.org
      PGADMIN_DEFAULT_PASSWORD: Geheim1!
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db:postgis-db
    volumes: 
      - ./pgadmin/servers.json:/pgadmin4/servers.json

  pop:
    container_name: population-service
    image: population-service
    env_file:
      - .env
    ports:
      - 3333:3333
    restart: on-failure
    depends_on:
      - db

volumes:
  pop-data:
    external: false